### PR TITLE
Title Change from 2017 to 2018 for some screens

### PR DESCRIPTION
**Pull request by omi10859**
Issue: https://github.com/pythonindia/PyCon-Mobile-App/issues/49

### CODE REVIEW

**Comment by omi10859** [comment]
Now App can fetch event name from event.json and place it on: 
- On Welcome Screen 
- TopBar

**Comment by akshayaurora** [comment]
Does not make sense to be reading the files again and again. Plus any IO bound op should always be done in a background thread.

**Comment by omi10859** [comment]
so maybe i should delete my second commit for now? @akshayaurora

**Comment by akshayaurora** [comment]
@omi10859 yes,  please do a new pr

**Pull request closed without merging**
