### PR TITLE
Screens

### PR DESCRIPTION
**Pull request by kiok46**
The structure and purpose:
```
data/
    images/
        social/
            facebook.png
            twitter.png
            github.png
            linkedin.png
            website.png
            proposal.png
        back_button.png # for navigating back from speaker screen,
    jsonfiles/
        ...
        schedule.json # Getting schedule data from this file.
        tracks.json # Getting speaker data from here.
uix/
    cards/
        __init__.py # import these from uix/schedulecards
        cardscontainer.py # Contains the ScrollView and a Container (for padding)
        schedulecard.py # These are the cards you see for each talk, (ButtonBehavior included)
        talkdetailcard.py 
        speakerdetailcard.py 
        sponsordetailcard.py
    screens/
        schedulescreen.py
        venuescreen.py
        speakerdetailscreen.py  # Contains SocialButton's implementation too.
        sponsorscreen.py
    tabbedpanels/
        __init__.py # Tabbed Panels 2 types: Top Blue ones for dates and the ones at the bottom for halls. The DateTabbedPanel is a parent to HallTabbedPanel
```

### CODE REVIEW

**Comment by kiok46** [comment]
schedule_screen

**Comment by kiok46** [comment]
Speaker Screen.

screen shot 2017-10-26 at 6 30 09 pm

**Comment by kiok46** [comment]
screen shot 2017-10-28 at 12 14 29 pm

**Comment by kiok46** [comment]
screen shot 2017-10-28 at 4 27 06 pm

**Comment by akshayaurora** [comment]
@kiok46 thanks 👍

**Pull request merged**
